import type { Metadata } from 'next';
import './globals.css';
import { PageLoader, IntroLoader, GoogleAnalytics } from '@/components';
import { generateOrganizationSchema, generateWebsiteSchema, siteConfig } from '@/lib/seo';
import RefIdCookieSetter from '@/components/RefIdCookieSetter';

import { cookies } from 'next/headers';
import { SponsorProvider } from '@/app/providers/SponsorProvider';

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: 'EDST | Social Media Growth & Viral Marketing Agency',
    template: '%s | EDST',
  },
  description: 'The marketing ecosystem that never sleeps. EDST helps 30K+ creators, brands, and entrepreneurs blow up with viral campaigns, social growth, and real results worldwide.',
  keywords: [
    'social media growth agency',
    'viral marketing',
    'Instagram growth',
    'TikTok marketing',
    'creator marketing',
    'influencer marketing',
    'music marketing',
    'brand marketing',
    'EDST',
  ],
  authors: [{ name: 'EDST', url: siteConfig.url }],
  creator: 'EDST',
  publisher: 'EveryDay Success Team LLC',
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: [
      { url: '/favicon.svg', sizes: '180x180', type: 'image/svg+xml' },
    ],
    shortcut: '/favicon.svg',
  },
  manifest: '/manifest.json',
  openGraph: {
    title: 'EDST | Social Media Growth & Viral Marketing Agency',
    description: 'The marketing ecosystem that never sleeps. 30K+ clients. 20B+ impressions. Real results.',
    url: siteConfig.url,
    siteName: siteConfig.name,
    locale: siteConfig.locale,
    type: 'website',
    // OG image is auto-generated by /app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'EDST | Social Media Growth & Viral Marketing Agency',
    description: 'The marketing ecosystem that never sleeps. 30K+ clients. 20B+ impressions.',
    creator: siteConfig.twitterHandle,
    site: siteConfig.twitterHandle,
    // Twitter image is auto-generated by /app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: siteConfig.url,
  },
  verification: {
    // Add these when you have them:
    // google: 'your-google-verification-code',
  },
};

// Structured Data for SEO (JSON-LD) - Multiple schemas for rich results
const organizationSchema = generateOrganizationSchema();
const websiteSchema = generateWebsiteSchema();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sponsor = cookies().get('sponsor')?.value || null;

  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* Organization Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        {/* Website Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body className="antialiased bg-edst-black text-edst-white">
        <GoogleAnalytics />
        <IntroLoader />
        <PageLoader />
        <RefIdCookieSetter />
        <SponsorProvider sponsor={sponsor}>
          {children}
        </SponsorProvider>
        
      </body>
    </html>
  );
}
